config/routes.rb
Rails.application.routes.draw do
  resources :type_debts
  resources :type_accounts
  resources :debts
  resources :accounts
  devise_for :users
  root 'accounts#index'
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :type_accounts
  belongs_to :user
end

app/models/debt.rb
class Debt < ActiveRecord::Base
  belongs_to :type_debts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = current_user.accounts.build
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = current_user.accounts.build(account_params)
    @account.user_id = current_user.id
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name_account, :amount_account, :type_account, :currency)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
  before_action :set_debt, only: [:show, :edit, :update, :destroy]

  # GET /debts
  # GET /debts.json
  def index
    @debts = Debt.all
  end

  # GET /debts/1
  # GET /debts/1.json
  def show
  end

  # GET /debts/new
  def new
    @debt = Debt.new
  end

  # GET /debts/1/edit
  def edit
  end

  # POST /debts
  # POST /debts.json
  def create
    @debt = Debt.new(debt_params)

    respond_to do |format|
      if @debt.save
        format.html { redirect_to @debt, notice: 'Debt was successfully created.' }
        format.json { render :show, status: :created, location: @debt }
      else
        format.html { render :new }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debts/1
  # PATCH/PUT /debts/1.json
  def update
    respond_to do |format|
      if @debt.update(debt_params)
        format.html { redirect_to @debt, notice: 'Debt was successfully updated.' }
        format.json { render :show, status: :ok, location: @debt }
      else
        format.html { render :edit }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debts/1
  # DELETE /debts/1.json
  def destroy
    @debt.destroy
    respond_to do |format|
      format.html { redirect_to debts_url, notice: 'Debt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debt
      @debt = Debt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debt_params
      params.require(:debt).permit(:name_debt, :amount_debt, :id_type_debts)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/helpers/type_accounts_helper.rb
module TypeAccountsHelper
end

app/helpers/type_debts_helper.rb
module TypeDebtsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label 'Type', class: 'control-label' %>
    <div class='controls'>
      <%= f.select(:type_account, options_for_select([['Cash', 'Cash'],['Bank card', 'Bank card'],['Money box', 'Money box']])) %>
    </div>
  </div>

  <div class="field">
    <%= f.label :name_account %><br>
    <%= f.text_field :name_account %>
  </div>
  <div class="field">
    <%= f.label :amount_account %><br>
    <%= f.text_field :amount_account %>
    <%= f.select(:currency, options_for_select([['$', '$'],['Rub', 'Rub'],['UAH', 'UAH'],['EUR', 'EUR']])) %>
  </div>

    <div class='controls'>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><h1>Listing Accounts</h1></div>
  <div class="panel-body">
    <%= link_to 'New Account', new_account_path %>
    <p id="notice"><%= notice %></p>
  </div>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>User</th>
      <th>Name account</th>
      <th>Amount account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <th><%= account.user.email %></th>
        <td><%= account.name_account %></td>
        <td><%= account.amount_account %></td>
        <td><%= account.currency %></td>

        <td>
          <% if user_signed_in? %>
            <% if account.user_id == current_user.id %>
              <td><%= link_to 'Show', account %></td>
              <td><%= link_to 'Edit', edit_account_path(account) %></td>
              <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type account:</strong>
  <%= @account.type_account %>
</p>

<p>
  <strong>Name account:</strong>
  <%= @account.name_account %>
</p>

<p>
  <strong>Amount account:</strong>
  <%= @account.amount_account %>
  <%= @account.currency %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/debts/_form.html.erb
<%= form_for(@debt) do |f| %>
  <% if @debt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@debt.errors.count, "error") %> prohibited this debt from being saved:</h2>

      <ul>
      <% @debt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.collection_select(:id_type_debts, TypeDebt.all, :id, :type_debt) %><br>
    <%= f.label :name_debt %><br>
    <%= f.text_field :name_debt %>
  </div>
  <div class="field">
    <%= f.label :amount_debt %><br>
    <%= f.text_field :amount_debt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/debts/edit.html.erb
<h1>Editing Debt</h1>

<%= render 'form' %>

<%= link_to 'Show', @debt %> |
<%= link_to 'Back', debts_path %>

app/views/debts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Debts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name debt</th>
      <th>Amount debt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @debts.each do |debt| %>
      <tr>
        <td><%= debt.name_debt %></td>
        <td><%= debt.amount_debt %></td>
        <td><%= link_to 'Show', debt %></td>
        <td><%= link_to 'Edit', edit_debt_path(debt) %></td>
        <td><%= link_to 'Destroy', debt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Debt', new_debt_path %>

app/views/debts/new.html.erb
<h1>New Debt</h1>

<%= render 'form' %>

<%= link_to 'Back', debts_path %>

app/views/debts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name debt:</strong>
  <%= @debt.name_debt %>
</p>

<p>
  <strong>Amount debt:</strong>
  <%= @debt.amount_debt %>
</p>

<p>
  <strong>Type account:</strong>
  <%= @debt.id_type_debts %>
</p>

<%= link_to 'Edit', edit_debt_path(@debt) %> |
<%= link_to 'Back', debts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FamilyBudget</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="container">
        <div class="navbar-header">
          <%= link_to 'Family Budget', root_path, class: 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Accounts', accounts_path %></li>
            <li><%= link_to 'Debts', debts_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if user_signed_in? %>
                <%= link_to current_user.email, class: 'navbar-right navbar-text navbar-link'%>
                <li>
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
                <%= link_to 'Sign Up', new_user_registration_path %>
              <% end %>
            </li>
            <li>
              <% if user_signed_in? %>
              <% else %>
                <%= link_to 'Log In', new_user_session_path %>
              <% end %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
      </div>
    </nav>
  <div class="container">

    <%= yield %>
  </div>
</body>
</html>